### ISSUE TITLE
Credit Card Address Error

### ISSUE THREAD

**Issue by xzitlou** [InteliClic/UltraCart-Checkout-API#1]
Hi,
I'm using this API in a website, but there is a 404 error at the end of the checkout (in the upsell) when the customer put a wrong address, I want to know if I can make a validation for that.

The website is garcinia.com and the error message was encode in the URL:

<table>
<tr>
<td class="ucErrorMessageText">AVS Code</td>
<td class="ucErrorMessageText">N</td>
</tr>
<tr>
<td class="ucErrorMessageText">Authorization Code</td>
<td class="ucErrorMessageText">022095</td>
</tr>
<tr>
<td class="ucErrorMessageText">Response Code</td>
<td class="ucErrorMessageText">Declined - 2</td>
</tr>
<tr>
<td class="ucErrorMessageText">Response Reason Code</td>
<td class="ucErrorMessageText">27</td>
</tr>
<tr>
<td class="ucErrorMessageText">Response Subcode</td>
<td class="ucErrorMessageText">2</td>
</tr>
<tr>
<td class="ucErrorMessageText">Response Text</td>
<td class="ucErrorMessageText">The transaction has been declined because of an AVS mismatch. The address provided does not match billing address of cardholder.</td>
</tr>
<tr>
<td class="ucErrorMessageText">Transaction ID</td>
<td class="ucErrorMessageText">5618025933</td>
</tr>
<tr>
<td class="ucErrorMessageText">rotatingTransactionGatewayCode</td>
<td class="ucErrorMessageText">Garcinia</td>
</tr>
<tr>
<td class="ucErrorMessageText">rotatingTransactionGatewayName</td>
<td class="ucErrorMessageText">Authorize.Net 3.1</td>
</tr>
</table>

**Comment by InteliClic** [comment]
I just sync'd a commit with the patch.
