### ISSUE TITLE
Pass  credit card & cvv through api

### ISSUE THREAD

**Issue by ghost** [InteliClic/UltraCart-Checkout-API#3]
Hi, It seems there no way to pass them using the api

**Comment by InteliClic** [comment]
UltraCart now requires that you use their hosted CreditCard field for PCI 4 compliance. CVV should still be accepted in the cart object.

**Comment by InteliClic** [comment]
UltraCart's hosted CreditCard fields also includes the CVV field. Please use that instead of the fields in the API. You can only pass the hashed values via the API or UltraCart will reject them.
